[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

[project]
name = "cityvision"
dynamic = ["description", "readme", "dependencies"]
version = "0.1.0"
authors = [
  {name = "Sahand Somi", email = "sahand.somi@edmonton.ca"}
]
maintainers = [
  {name = "Sahand Somi", email = "sahand.somi@edmonton.ca"}
]
license = {text = "AGPL-3.0"}
classifiers = [
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Development Status :: 3 - Alpha",
    "Natural Language :: English",
]
requires-python = ">=3.11"

[tool.setuptools.dynamic]
version = {attr = "cityvision.__version__"}
readme = {file = ["README.md"], content-type = "text/markdown"}
dependencies = {file = ["requirements.txt"]}
